name: Markdown Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  markdownlint:
    name: Lint markdown files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v24
        with:
          globs: '**/*.md'
          config: '.markdownlint.json'
